var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var RoundSchema = new Schema({
   areaOne: {type: String},
    areaTwo: {type: String},
    areaThree: {type: String},
    areaFour: {type: String},
    areaFive: {type: String},
    areaSix: {type: String},
    areaSeven: {type: String},
    areaEight: {type: String},
    areaNine: {type: String},
    //areaTen: {type: String},
    //areaEleven: {type: String},
    //areaTwelve: {type: String},
    //areaThirteen: {type: String},
    //areaFourteen: {type: String},
    //areaFifteen: {type: String},
    //areaSixteen: {type: String},
    //areaSeventeen: {type: String},
    //areaEighteen: {type: String},
    scoreOne: {type: Number},
    scoreTwo: {type: Number},
    scoreThree: {type: Number},
    scoreFour: {type: Number},
    scoreFive: {type: Number},
    scoreSix: {type: Number},
    scoreSeven: {type: Number},
    scoreEight: {type: Number},
    scoreNine: {type: Number},
    //scoreTen: {type: Number},
    //scoreEleven: {type: Number},
    //scoreTwelve: {type: Number},
    //scoreThirteen: {type: Number},
    //scoreFourteen: {type: Number},
    //scoreFifteen: {type: Number},
    //scoreSixteen: {type: Number},
    //scoreSeventeen: {type: Number},
    //scoreEighteen: {type: Number},
    scoreTotal: {type: Number},
    puttsOne: {type: Number},
    puttsTwo: {type: Number},
    puttsThree: {type: Number},
    puttsFour: {type: Number},
    puttsFive: {type: Number},
    puttsSix: {type: Number},
    puttsSeven: {type: Number},
    puttsEight: {type: Number},
    puttsNine: {type: Number},
    //puttsTen: {type: Number},
    //puttsEleven: {type: Number},
    //puttsTwelve: {type: Number},
    //puttsThirteen: {type: Number},
    //puttsFourteen: {type: Number},
    //puttsFifteen: {type: Number},
    //puttsSixteen: {type: Number},
    //puttsSeventeen: {type: Number},
    //puttsEighteen: {type: Number},
    puttsTotal: {type: Number},
    holesPlayed: {type: Number},
    date: {type: Date, default: Date.now}
});

module.exports = mongoose.model("Round", RoundSchema);